title: Keerthana Radhakrishnan
#logo: /assets/img/headshot_circle.png
description: Mechatronics / Robotics / Drones / Embedded systems / Ardupilot / PX4 / Computer Vision
show_downloads: false
theme: jekyll-theme-cayman
